services:
  nginx:
    # image: nginx:latest
    build:
      context: ./docker/nginx
    restart: always
    ports:
      - 2000:80
    volumes:
      - ./docker/nginx/static-site:/usr/share/nginx/html

  redis:
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379
    networks:
      - api_network

  api:
    image: task-manager:0.1
    restart: always
    ports:
      - 8086:8085
    environment:
      REDIS_HOST: redis
    networks:
      - api_network

networks:
  api_network:
